# Generated by Django 5.2.5 on 2025-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedPassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('s_name', models.CharField(blank=True, max_length=250, null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('class_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'verified_pass_data',
            },
        ),
    ]
